function model = modelPathogen(options)
% MODELPATHOGEN  The pathogen preset: port of the pathogen model stored in
% slow-sand-filtration/thesis_model.mat (the model exercised by
% @SDfilter/run_pathogen.m and example.m / srun_pathogen.m).
%
%   model = modelPathogen()
%   model = modelPathogen(WaterFactor=1e-3, SandPathogen=0.0, DarkRespiration=1e-3)
%
% It extends the Lund/Rosenqvist ecology with a pathogen indicator (PAT) and two
% extra reactions -- pathogen inactivation (natural die-off) and bacterivory
% (predation of pathogens, promoted by heterotrophs). Components are HET, PHO,
% POM and PAT as particulates and O2, IC, NH4, HPO4, DOM as liquids.
%
% The values below are the verbatim thesis_model.mat contents; note this model
% uses its own unit convention (densities ~1, tau = 1e-3), distinct from
% modelLund -- do NOT copy rates between the two presets.
%
% Two mechanisms specific to the pathogen model map onto general fields:
%   * WaterFactor (MATLAB r_water = [0...0 1]*water_factor) -> per-reaction
%     Reaction.EfficiencyFlowing: every reaction is inert in the flowing phase
%     except bacterivory, which acts there scaled by WaterFactor.
%   * SandPathogen -> PAT's Particle.SandAttachmentFactor: pathogens attach to
%     bare sand at a fraction of their biofilm-attachment rate.
%
% The bacterivory Monod term is HET-based: run_pathogen computes
% Xb(:,1)/(Xb(:,1) + kPred) (HET is column 1), even though MATLAB parks kPred in
% the DOM row of the "Bacterivory" kinetic-parameter column. We therefore key its
% half-saturation on "HET", reproducing the solver's actual kinetics.
%
% DarkRespiration is the phototroph baseline light factor (the authoritative
% code's global fdark, carried here by the light-dependent reaction's
% MinimumLightFactor). Defaults are the base-case values from example.m.
%
% Mirror of julia/src/presets/modelPathogen.jl -- keep the two in sync.

    arguments
        options.WaterFactor (1,1) double = 1e-3;
        options.SandPathogen (1,1) double = 0.0;
        options.DarkRespiration (1,1) double = 1e-3;
    end

    densityParticle = 1.2;
    dispersivity = 1.00E-03;
    attenuationParticle = 0.094;

    HET = Particle(Name="HET", Density=densityParticle, Dispersivity=dispersivity, ...
                   Transport=0.1, AttachmentSand=1.0, AttachmentMatrix=1.0, ...
                   Attenuation=attenuationParticle);
    PHO = Particle(Name="PHO", Density=densityParticle, Dispersivity=dispersivity, ...
                   Transport=0.1, AttachmentSand=1.0, AttachmentMatrix=1.0, ...
                   Attenuation=attenuationParticle);
    POM = Particle(Name="POM", Density=densityParticle, Dispersivity=dispersivity, ...
                   Transport=0.01, AttachmentSand=0.0, AttachmentMatrix=0.0, ...
                   Attenuation=attenuationParticle);
    PAT = Particle(Name="PAT", Density=densityParticle, Dispersivity=dispersivity, ...
                   Transport=1.00E-06, AttachmentSand=2.0, AttachmentMatrix=2.0, ...
                   Attenuation=attenuationParticle, ...
                   SandAttachmentFactor=options.SandPathogen);

    densityLiquid = 1.0;
    O2 = Liquid(Name="O2", Density=densityLiquid, Dispersivity=dispersivity, ...
                TransportRate=1.0);
    IC = Liquid(Name="IC", Density=densityLiquid, Dispersivity=dispersivity, ...
                TransportRate=1.0);
    NH4 = Liquid(Name="NH4", Density=densityLiquid, Dispersivity=dispersivity, ...
                 TransportRate=1.0);
    HPO4 = Liquid(Name="HPO4", Density=densityLiquid, Dispersivity=dispersivity, ...
                  TransportRate=1.0);
    DOM = Liquid(Name="DOM", Density=densityLiquid, Dispersivity=dispersivity, ...
                 TransportRate=0.1);

    % Reactions 1-5 are the Lund ecology at the thesis_model rates; every one of
    % them is inert in the flowing phase (r_water = 0), hence EfficiencyFlowing=0.
    heterotrophGrowth = Reaction(Name="Heterotroph growth", IsLightDependent=false, ...
            NominalRate=0.02, ...
            TemperatureCorrectionFactor=1.047, ...
            EfficiencyFlowing=0.0, ...
            Order=dictionary("HET", 1.0), ...
            HalfSaturationConstants=dictionary("O2", 0.3, "NH4", 0.4, ...
                                        "HPO4", 2.00E-06, "DOM", 0.02), ...
            StoichiometricCoefficients=dictionary("HET", 1.0, ...
                                        "O2", -1.23168093, "IC", 0.3847619048, ...
                                        "NH4", -0.02476190476, "HPO4", -0.01412698413, ...
                                        "DOM", -1.587301587));

    phototrophGrowth = Reaction(Name="Phototroph growth", IsLightDependent=true, ...
            MinimumLightFactor=options.DarkRespiration, OptimalLightFactor=1.08, ...
            NominalRate=10.0, ...
            TemperatureCorrectionFactor=1.047, ...
            EfficiencyFlowing=0.0, ...
            Order=dictionary("PHO", 1.0), ...
            HalfSaturationConstants=dictionary("IC", 0.002, "NH4", 1.2, "HPO4", 0.02), ...
            StoichiometricCoefficients=dictionary("PHO", 1.0, ...
                                        "O2", 0.9300460829, "IC", -0.36, ...
                                        "NH4", -0.06, "HPO4", -0.01));

    heterotrophDeath = Reaction(Name="Heterotroph death", IsLightDependent=false, ...
            NominalRate=2.0, ...
            TemperatureCorrectionFactor=1.066, ...
            EfficiencyFlowing=0.0, ...
            Order=dictionary("HET", 1.0), ...
            StoichiometricCoefficients=dictionary("HET", -1.0, "POM", 0.9122807018, ...
                                        "O2", 0.02336243835, "NH4", 0.06526315789, ...
                                        "HPO4", 0.02087719298));

    phototrophDeath = Reaction(Name="Phototroph death", IsLightDependent=false, ...
            NominalRate=0.4, ...
            TemperatureCorrectionFactor=1.08, ...
            EfficiencyFlowing=0.0, ...
            Order=dictionary("PHO", 1.0), ...
            StoichiometricCoefficients=dictionary("PHO", -1.0, "POM", 0.6315789474, ...
                                        "O2", 0.2005093379, "NH4", 0.02210526316, ...
                                        "HPO4", 0.003684210526));

    hydrolysis = Reaction(Name="Hydrolysis", IsLightDependent=false, ...
            NominalRate=1.0, ...
            TemperatureCorrectionFactor=1.08, ...
            EfficiencyFlowing=0.0, ...
            Order=dictionary("HET", 1.0), ...
            HalfSaturationConstants=dictionary("POM/HET", 0.002), ...
            StoichiometricCoefficients=dictionary("POM", -1.0, "DOM", 1.0));

    % Pathogen die-off: first-order in PAT, no Monod, inert in the flowing phase.
    inactivation = Reaction(Name="Inactivation", IsLightDependent=false, ...
            NominalRate=0.4, ...
            TemperatureCorrectionFactor=1.08, ...
            EfficiencyFlowing=0.0, ...
            Order=dictionary("PAT", 1.0), ...
            StoichiometricCoefficients=dictionary("PAT", -1.0));

    % Bacterivory: first-order in PAT, HET-limited (Monod, K = kPred = 0.002),
    % removes PAT and returns biomass to HET. This is the only reaction active in
    % the flowing phase, scaled there by WaterFactor.
    bacterivory = Reaction(Name="Bacterivory", IsLightDependent=false, ...
            NominalRate=20.0, ...
            TemperatureCorrectionFactor=1.08, ...
            EfficiencyFlowing=options.WaterFactor, ...
            Order=dictionary("PAT", 1.0), ...
            HalfSaturationConstants=dictionary("HET", 0.002), ...
            StoichiometricCoefficients=dictionary("PAT", -1.0, "HET", 1.0));

    componentList = [HET; PHO; POM; PAT;
                     O2; IC; NH4; HPO4; DOM];
    reactionList = [heterotrophGrowth;
                    phototrophGrowth;
                    heterotrophDeath;
                    phototrophDeath;
                    hydrolysis;
                    inactivation;
                    bacterivory];

    model = Model(componentList, reactionList, ...
                  Kappa=1.00E-06, Zeta0=1.0, Zeta1=1/100, ...
                  DetachmentFunction=@(v) sqrt(abs(v) / 7.2), ...
                  WaterDensity=densityLiquid, ...
                  BiofilmPorosity=0.99, ...
                  OsmosisRate=1.00E-03);
end
