function model = modelLund(options)
    arguments
            options.WriteFile = false;
            % > 0 enables the phototroph metabolic split (plan
            % 2026-08-18-phototroph-respiration): appends a sixth reaction
            % "Phototroph respiration" (first-order in PHO, light-independent,
            % O2-Monod-limited, stoichiometry = reverse of phototroph growth)
            % at this nominal rate, and drops the growth reaction's dark floor
            % (MinimumLightFactor) to 0. Literature: kra = 0.0020-0.0210 /h,
            % avg 0.0115 /h = 0.276 /d (Campos2006 Table 3, Brown & Barnwell
            % 1987), theta_kra = 1.08. Default 0.0 reproduces the original
            % 5-reaction model exactly (goldens unchanged).
            options.PhototrophRespiration (1,1) {mustBeNumeric} = 0.0;
            % Wolf2007 storage fraction f (kg COD PG per kg COD PHO built) and
            % yield Y_PH/PG (ASSUMED 0.63, the ASM heterotroph yield; Wolf2007
            % Table VI leaves it unpinned).
            options.PGFraction (1,1) {mustBeNumeric} = 0.2;
            options.PGYield (1,1) {mustBeNumeric} = 0.63;
            % true = PG-in-excess variant: the storage pool is assumed never
            % limiting and is NOT tracked (no PG component); respiration's
            % light factor is the complement 1 - Steele(I) of the growth
            % factor. Deliberately mass-non-conservative toward the pool.
            options.PGExcess (1,1) logical = false;
    end

    densityParticle = 1.117E+03;
    attenuationParticle = 0.094;
    dispersivityParticle = 1.20E-02;
    HET =  Particle(Name="HET", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                             Transport=5.47, AttachmentSand=5.47E+02, AttachmentMatrix=5.47E+02,...
                             Attenuation=attenuationParticle);
    PHO =  Particle(Name="PHO", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                             Transport=5.47, AttachmentSand=5.47E+02, AttachmentMatrix=5.47E+02,...
                             Attenuation=attenuationParticle);
    POM =  Particle(Name="POM", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                             Transport=5.47, AttachmentSand=0.0, AttachmentMatrix=0.0,...
                             Attenuation=attenuationParticle);
    PAT =  Particle(Name="PAT", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                             Transport=5.47, AttachmentSand=5.47E+02, AttachmentMatrix=5.47E+02,...
                             Attenuation=attenuationParticle);
                    
    densityLiquid = 0.998E+03;
    dispersivityLiquid = 1.20E-02;
    O2 =  Liquid(Name="O2", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+02);
    IC =  Liquid(Name="IC", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+02);
    NH4 =  Liquid(Name="NH4", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+02);
    HPO4 =  Liquid(Name="HPO4", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+02);
    DOM =  Liquid(Name="DOM", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=3.00E+02);


    heterotrophGrowth =  Reaction(Name="Heterotroph growth", IsLightDependent=false, ...
            NominalRate=1.81E-02, ... 
            TemperatureCorrectionFactor=1.047, ...
            Order=dictionary("HET", 1), ...
            HalfSaturationConstants=dictionary("O2", 3.00E-03, "DOM", 2.00E-04, "NH4", 4.00E-03, "HPO4", 1.40E-08), ...
            StoichiometricCoefficients=dictionary("HET", 1.0, ...
                                        "O2", -1.2317, "IC", 0.3848, "NH4", -0.0248, "HPO4", -0.0141, "DOM", -1.5873));

    phototrophGrowth =  Reaction(Name="Phototroph growth", IsLightDependent=true, ...
            MinimumLightFactor=0.01, OptimalLightFactor=1.814E-02, ...
            NominalRate=5.50, ...
            TemperatureCorrectionFactor=1.047, ...
            Order=dictionary("PHO", 1), ...
            HalfSaturationConstants=dictionary("IC", 2.00E-05, "NH4", 1.20E-02, "HPO4", 1.68E-04), ...
            StoichiometricCoefficients=dictionary("PHO", 1.0, ...
                                        "O2", 0.9301, "IC", -0.3600, "NH4", -0.0600, "HPO4", -0.0100));

    heterotrophDeath =  Reaction(Name="Heterotroph death", IsLightDependent=false, ...
            NominalRate=2.00, ...
            TemperatureCorrectionFactor=1.066, ...
            Order=dictionary("HET", 1), ...
            StoichiometricCoefficients=dictionary("HET", -1.0, "POM", 0.9123, ...
                                        "O2", 0.0234, "NH4", 0.0653, "HPO4", 0.0209));

    phototrophDeath =  Reaction(Name="Phototroph death", IsLightDependent=false, ...
            NominalRate=4.00E-01, ...
            TemperatureCorrectionFactor=1.080, ...
            Order=dictionary("PHO", 1), ...
            StoichiometricCoefficients=dictionary("PHO", -1.0, "POM", 0.6316, ...
                                        "O2", 0.2005, "NH4", 0.0221, "HPO4", 0.0037));

    hydrolysis =  Reaction(Name="Hydrolysis", IsLightDependent=false, ...
            NominalRate=9.00E-02, ...
            TemperatureCorrectionFactor=1.080, ...
            Order=dictionary("HET", 1), ...
            HalfSaturationConstants=dictionary("POM/HET", 2.00E-05), ...
            StoichiometricCoefficients=dictionary("POM", -1.0, "DOM", 1.0));
                                    

    componentList = [HET; PHO; POM; PAT; 
                      O2; IC; NH4; HPO4; DOM];
    reactionList = [heterotrophGrowth; 
                    phototrophGrowth; 
                    heterotrophDeath; 
                    phototrophDeath; 
                    hydrolysis];
    if options.PhototrophRespiration > 0 && options.PGExcess
        % PG-in-excess variant (Jaime, 2026-08-19): growth keeps the original
        % Lund row (floor retired); respiration is Wolf2007 r6 WITHOUT the PG
        % column, light factor = 1 - Steele(I): biomass built in dark places,
        % consuming NH4 and O2, releasing IC.
        Y = options.PGYield;
        phototrophGrowth.MinimumLightFactor = 0.0;
        reactionList(2) = phototrophGrowth;
        phototrophRespiration = Reaction(Name="Phototroph respiration", ...
                NominalRate=options.PhototrophRespiration, ...
                IsLightComplement=true, ...
                TemperatureCorrectionFactor=1.08, ...
                Order=dictionary("PHO", 1), ...
                HalfSaturationConstants=dictionary("O2", 3.00E-03), ...
                StoichiometricCoefficients=dictionary( ...
                        ["PHO", "O2", "IC", "NH4", "HPO4"], ...
                        [Y, -(1.0667 - 0.9301*Y), 0.4 - 0.36*Y, -0.06*Y, -0.01*Y]));
        reactionList = [reactionList; phototrophRespiration];
    elseif options.PhototrophRespiration > 0
        % Wolf2007 (PHOBIA): photosynthesis stores the f-fraction into an
        % internal polyglucose pool PG (CH2O: +1.0667 O2, -0.4 C per unit PG);
        % dark respiration (r6) grows PHO on PG, consuming NH4 and O2. PG is
        % transport-identical to PHO (intracellular) and appended as the 5th
        % particle so Lund-structure indices survive. Dark floor retired.
        f = options.PGFraction;
        Y = options.PGYield;
        PG = Particle(Name="PG", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                      Transport=5.47, AttachmentSand=5.47E+02, AttachmentMatrix=5.47E+02, ...
                      Attenuation=attenuationParticle);
        componentList = [componentList(1:4); PG; componentList(5:end)];
        phototrophGrowth.MinimumLightFactor = 0.0;
        phototrophGrowth.StoichiometricCoefficients = dictionary( ...
                ["PHO", "PG", "O2", "IC", "NH4", "HPO4"], ...
                [1.0, f, 0.9301 + 1.0667*f, -(0.3600 + 0.4*f), -0.0600, -0.0100]);
        reactionList(2) = phototrophGrowth;
        % r6: rate 0.1*q_max = 0.55/d (Tillmann & Rick 2001), first-order in
        % PHO, min-Monod over O2 and the PG/PHO quotient (K_S,PH,PG = 0.005,
        % Wolf Table VI), dark-only via K_inh/(K_inh + I), K_inh = 8e-5
        % normalized by I_opt = 1.814e-2. Columns are the difference of the
        % PG-synthesis and biomass rows, so COD/elements balance exactly.
        phototrophRespiration = Reaction(Name="Phototroph respiration", ...
                NominalRate=options.PhototrophRespiration, ...
                LightInhibition=8e-5/1.814e-2, ...
                TemperatureCorrectionFactor=1.08, ...
                Order=dictionary("PHO", 1), ...
                HalfSaturationConstants=dictionary(["O2", "PG/PHO"], [3.00E-03, 0.005]), ...
                StoichiometricCoefficients=dictionary( ...
                        ["PG", "PHO", "O2", "IC", "NH4", "HPO4"], ...
                        [-1.0, Y, -(1.0667 - 0.9301*Y), 0.4 - 0.36*Y, -0.06*Y, -0.01*Y]));
        reactionList = [reactionList; phototrophRespiration];
    end
    model = Model(Components=componentList, ...
                 Kappa=1.00E-06, Zeta0=1.00E+06, Zeta1=1/100, ...
                 DetachmentFunction=@(v) sqrt(v / 7.2), ...
                 BiofilmPorosity=0.99, ...
                 OsmosisRate=1.00E-07, ...
                 Reactions=reactionList);

    if options.WriteFile
        save("./LundMPCModel.mat", "model");
    end
end