function model = modelLund(options)
    arguments
            options.WriteFile = false;
    end
    import  *

    densityParticle = 1.117E+03;
    attenuationParticle = 0.094;
    dispersivityParticle = 1.20E-02;
    HET =  Particle(Name="HET", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                             Transport=5.47, AttachmentSand=5.47E+02, AttachmentMatrix=5.47E+02,...
                             Attenuation=attenuationParticle);
    PHO =  Particle(Name="PHO", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                             Transport=5.47, AttachmentSand=5.47E+02, AttachmentMatrix=5.47E+02,...
                             Attenuation=attenuationParticle);
    POM =  Particle(Name="POM", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                             Transport=5.47, AttachmentSand=0.0, AttachmentMatrix=0.0,...
                             Attenuation=attenuationParticle);
    PAT =  Particle(Name="PAT", Density=densityParticle, Dispersivity=dispersivityParticle, ...
                             Transport=5.47, AttachmentSand=5.47E+02, AttachmentMatrix=5.47E+02,...
                             Attenuation=attenuationParticle);
                    
    densityLiquid = 0.998E+03;
    dispersivityLiquid = 1.20E-02;
    O2 =  Liquid(Name="O2", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+01);
    IC =  Liquid(Name="IC", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+01);
    NH4 =  Liquid(Name="NH4", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+01);
    HPO4 =  Liquid(Name="HPO4", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+01);
    DOM =  Liquid(Name="DOM", Density=densityLiquid, Dispersivity=dispersivityLiquid, ...
                            Transport=6.00E+01);


    heterotrophGrowth =  Reaction(Name="Heterotroph growth", IsLightDependent=false, ...
            NominalRate=1.81E-02, ... 
            TemperatureCorrectionFactor=1.047, ...
            Order=dictionary("HET", 1), ...
            HalfSaturationConstants=dictionary("O2", 3.00E-03, "DOM", 2.00E-04, "NH4", 4.00E-03, "HPO4", 1.40E-08), ...
            StoichiometricCoefficients=dictionary("HET", 1.0, ...
                                        "O2", -1.2317, "IC", 0.3848, "NH4", -0.0248, "HPO4", -0.0141, "DOM", -1.5873));

    phototrophGrowth =  Reaction(Name="Phototroph growth", IsLightDependent=true, ...
            MinimumLightFactor=0.01, OptimalLightFactor=1.814E-02, ...
            NominalRate=5.50, ...
            TemperatureCorrectionFactor=1.047, ...
            Order=dictionary("PHO", 1), ...
            HalfSaturationConstants=dictionary("IC", 2.00E-05, "NH4", 1.20E-02, "HPO4", 1.68E-04), ...
            StoichiometricCoefficients=dictionary("PHO", 1.0, ...
                                        "O2", 0.9301, "IC", -0.3600, "NH4", -0.0600, "HPO4", -0.0100));

    heterotrophDeath =  Reaction(Name="Heterotroph death", IsLightDependent=false, ...
            NominalRate=2.00, ...
            TemperatureCorrectionFactor=1.066, ...
            Order=dictionary("HET", 1), ...
            StoichiometricCoefficients=dictionary("HET", -1.0, "POM", 0.9123, ...
                                        "O2", 0.0234, "NH4", 0.0653, "HPO4", 0.0209));

    phototrophDeath =  Reaction(Name="Phototroph death", IsLightDependent=false, ...
            NominalRate=4.00E-01, ...
            TemperatureCorrectionFactor=1.080, ...
            Order=dictionary("PHO", 1), ...
            StoichiometricCoefficients=dictionary("PHO", -1.0, "POM", 0.6316, ...
                                        "O2", 0.2005, "NH4", 0.0221, "HPO4", 0.0037));

    hydrolysis =  Reaction(Name="Hydrolysis", IsLightDependent=false, ...
            NominalRate=9.00E-02, ...
            TemperatureCorrectionFactor=1.080, ...
            Order=dictionary("HET", 1), ...
            HalfSaturationConstants=dictionary("POM/HET", 2.00E-05), ...
            StoichiometricCoefficients=dictionary("POM", -1.0, "DOM", 1.0));
                                    

    componentList = [HET; PHO; POM; PAT; 
                      O2; IC; NH4; HPO4; DOM];
    reactionList = [heterotrophGrowth; 
                    phototrophGrowth; 
                    heterotrophDeath; 
                    phototrophDeath; 
                    hydrolysis];
    model = Model(Components=componentList, ...
                 Kappa=1.00E-06, Zeta0=1.00E+06, Zeta1=1/100, ...
                 DetachmentFunction=@(v) sqrt(v / 7.2), ...
                 BiofilmPorosity=0.99, ...
                 OsmosisRate=1.00E-07, ...
                 Reactions=reactionList);

    if options.WriteFile
        save("./LundMPCModel.mat", "model");
    end
end